---
- name: Create Azure Windows VM
  hosts: localhost
  connection: local
  vars_prompt:
    - name: password
      prompt: "Enter local administrator password"

  tasks:
 
  - include_vars: namevars.yml
  
  - name: Create resource group
    azure_rm_resourcegroup:
      name: ansiblerg
      location: eastus

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: ansiblerg
      name: ansible-vnet
      address_prefixes: "192.168.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: ansiblerg
      name: subnet
      address_prefix: "192.168.1.0/24"
      virtual_network: ansible-vnet

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: ansiblerg
      allocation_method: Static
      name: "pip_{{ vm1 }}"
    register: output_ip_address

  - name: Output public IP
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}"
  
  - name: Create Network Security Group
    azure_rm_securitygroup:
      resource_group: ansiblerg
      name: networkSecurityGroup
      rules:
        - name: 'allow_rdp'
          protocol: Tcp
          destination_port_range: 3389
          access: Allow
          priority: 1001
          direction: Inbound
        - name: 'allow_web_traffic'
          protocol: Tcp
          destination_port_range:
            - 80
            - 443
          access: Allow
          priority: 1002
          direction: Inbound
        - name: 'allow_powershell_remoting'
          protocol: Tcp
          destination_port_range: 
            - 5985
            - 5986
          access: Allow
          priority: 1003
          direction: Inbound

  - name: Create a network interface
    azure_rm_networkinterface:
      name: "nic_{{ vm1 }}"
      resource_group: ansiblerg
      virtual_network: ansible-vnet
      subnet_name: subnet
      security_group: networkSecurityGroup
      ip_configurations:
        - name: default
          public_ip_address_name: "pip_{{ vm1 }}"
          primary: True

  - name: Create 1st VM
    azure_rm_virtualmachine:
      resource_group: ansiblerg
      name: "{{ vm1 }}"
      vm_size: Standard_DS1_v2
      admin_username: asharsidd
      admin_password: "{{ password }}"
      network_interfaces: "nic_{{ vm1 }}"
      managed_disk_type: Standard_LRS
      os_type: Windows
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2019-Datacenter
        version: latest
    no_log: false

  - name: Create VM script extension to enable HTTPS WinRM listener
    azure_rm_virtualmachineextension:
      name: winrm-extension
      resource_group: ansiblerg
      virtual_machine_name: "{{ vm1 }}"
      publisher: Microsoft.Compute
      virtual_machine_extension_type: CustomScriptExtension
      type_handler_version: '1.9'
      settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"}'
      auto_upgrade_minor_version: true

  - name: Get facts for one Public IP
    azure_rm_publicipaddress_info:
      resource_group: ansiblerg
      name: "pip_{{ vm1 }}"
    register: publicipaddresses

  - name: set public ip address fact
    set_fact: publicipaddress="{{ publicipaddresses | json_query('publicipaddresses[0].ip_address')}}"

  - name: wait for the WinRM port to come online
    wait_for:
      port: 5986
      host: '{{ publicipaddress }}'
      timeout: 600

  - name: Create 2nd public IP address
    azure_rm_publicipaddress:
      resource_group: ansiblerg
      allocation_method: Static
      name: "pip_{{ vm2 }}"
    register: output_ip_address

  - name: Output public IP
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}"
  
  - name: Create a network interface
    azure_rm_networkinterface:
      name: "nic_{{ vm2 }}"
      resource_group: ansiblerg
      virtual_network: ansible-vnet
      subnet_name: subnet
      security_group: networkSecurityGroup
      ip_configurations:
        - name: default
          public_ip_address_name: "pip_{{ vm2 }}"
          primary: True

  - name: Create 2nd VM
    azure_rm_virtualmachine:
      resource_group: ansiblerg
      name: "{{ vm2 }}"
      vm_size: Standard_DS1_v2
      admin_username: asharsidd
      admin_password: "{{ password }}"
      network_interfaces: "nic_{{ vm2 }}"
      managed_disk_type: Standard_LRS
      os_type: Windows
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2019-Datacenter
        version: latest
    no_log: false

  - name: Create VM script extension to enable HTTPS WinRM listener
    azure_rm_virtualmachineextension:
      name: winrm-extension
      resource_group: ansiblerg
      virtual_machine_name: "{{ vm2 }}"
      publisher: Microsoft.Compute
      virtual_machine_extension_type: CustomScriptExtension
      type_handler_version: '1.9'
      settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"}'
      auto_upgrade_minor_version: true

  - name: Get facts for one Public IP
    azure_rm_publicipaddress_info:
      resource_group: ansiblerg
      name: "pip_{{ vm2 }}"
    register: publicipaddresses

  - name: set public ip address fact
    set_fact: publicipaddress="{{ publicipaddresses | json_query('publicipaddresses[0].ip_address')}}"

  - name: wait for the WinRM port to come online
    wait_for:
      port: 5986
      host: '{{ publicipaddress }}'
      timeout: 600