- hosts: localhost
  connection: local
  tasks:
    - name: Create Resource Group
      azure_rm_resourcegroup:
        name: ansible_rg
        location: eastus
      register: rg
    - debug:
        var: rg     